deployment:
  region:
    dev: eu-central-1   # Frankfurt
    test: eu-west-1     # Ireland
    prod: us-east-1     # N.Virginia
  globalStages: # need for per-developer stages
    dev: dev
    test: test
    prod: prod

  # If you need to run Lambda inside VPC uncomment below  
  # and configure SG and subnets below:
  #
  # vpc:
  #   dev:                  
  #     securityGroupId: sg-abcdefgh
  #     subnetId1: subnet-12345678
  #     subnetId2: subnet-12345678
  #   test:
  #     securityGroupId: sg-abcdefgh
  #     subnetId1: subnet-12345678
  #     subnetId2: subnet-12345678
  #   prod:
  #     securityGroupId: sg-abcdefgh
  #     subnetId1: subnet-12345678
  #     subnetId2: subnet-12345678
  #
  #
  #  Next in serverless.yml in Lambda function section add following:
  #   vpc:
  #     securityGroupIds:
  #       - ${self:custom.deployment.vpc.${self:provider.stage}.securityGroupId}
  #     subnetIds:
  #       - ${self:custom.deployment.vpc.${self:provider.stage}.subnetId1}
  #       - ${self:custom.deployment.vpc.${self:provider.stage}.subnetId2}